
let dropCourseId = null;

async function registerUser(){const e=document.getElementById('regEmail').value,p=document.getElementById('regPassword').value;if(!e||!p){alert('Please enter email and password');return;}try{const r=await fetch('/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})});const d=await r.json();alert(d.message);localStorage.setItem('userEmail',e);}catch(e){alert('Registration failed');}}
async function loginUser(){const e=document.getElementById('loginEmail').value,p=document.getElementById('loginPassword').value;if(!e||!p){alert('Please enter email and password');return;}try{const r=await fetch('/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})});const d=await r.json();alert(d.message);localStorage.setItem('userEmail',e);}catch(e){alert('Login failed');}}
async function fetchCourses(){try{const r=await fetch('/courses');const d=await r.json();const s=document.getElementById('course-select');if(s){s.innerHTML='<option value="">— Choose a course —</option>';d.forEach(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=`${c.name} (Seats left: ${c.seats})`;s.appendChild(o);});}}catch(e){alert('Cannot load courses');}}
async function registerCourse(){const id=parseInt(document.getElementById('course-select').value),e=localStorage.getItem('userEmail');if(!id){alert('Select a course');return;}try{const r=await fetch('/register-course',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId:id,userEmail:e})});const d=await r.json();alert(d.message);fetchCourses();loadEnrolled();}catch(e){alert('Course registration failed');}}
function showModal(courseId){dropCourseId=courseId;document.getElementById('confirmModal').style.display='block';}
function closeModal(){document.getElementById('confirmModal').style.display='none';}
async function confirmDrop(){if(dropCourseId==null)return;const e=localStorage.getItem('userEmail');try{const r=await fetch('/drop-course',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId:dropCourseId,userEmail:e})});const d=await r.json();alert(d.message);fetchCourses();loadEnrolled();closeModal();}catch(e){alert('Drop course failed');closeModal();}}
async function loadEnrolled(){const e=localStorage.getItem('userEmail');const t=document.querySelector('#enrolled-table tbody');if(!t)return;const r=await fetch(`/my-schedule?email=${encodeURIComponent(e)}`);const d=await r.json();t.innerHTML='';d.forEach(c=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${c.id}</td><td>${c.name}</td><td>TBD</td><td>3</td><td><button onclick="showModal(${c.id})">Drop</button></td>`;t.appendChild(tr);});}
async function pay(){try{const r=await fetch('/pay',{method:'POST',headers:{'Content-Type':'application/json'}});const d=await r.json();alert(d.message);}catch(e){alert('Payment failed');}}
function logout(){localStorage.removeItem('userEmail');window.location.href='login.html';}
document.addEventListener('DOMContentLoaded',()=>{if(document.getElementById('course-select'))fetchCourses();if(document.getElementById('register-btn'))document.getElementById('register-btn').addEventListener('click',registerCourse);if(document.querySelector('#enrolled-table'))loadEnrolled();});
